// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package repo

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStoreToken = `-- name: CreateStoreToken :exec
INSERT INTO store_tokens (
    session_id, token_hash, account_id, description,
    packages, channels, permissions,
    valid_since, valid_until, revoked_at, revoked_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateStoreTokenParams struct {
	SessionID   string
	TokenHash   string
	AccountID   string
	Description *string
	Packages    json.RawMessage
	Channels    json.RawMessage
	Permissions json.RawMessage
	ValidSince  time.Time
	ValidUntil  time.Time
	RevokedAt   pgtype.Timestamptz
	RevokedBy   *string
}

func (q *Queries) CreateStoreToken(ctx context.Context, arg CreateStoreTokenParams) error {
	_, err := q.db.Exec(ctx, createStoreToken,
		arg.SessionID,
		arg.TokenHash,
		arg.AccountID,
		arg.Description,
		arg.Packages,
		arg.Channels,
		arg.Permissions,
		arg.ValidSince,
		arg.ValidUntil,
		arg.RevokedAt,
		arg.RevokedBy,
	)
	return err
}

const ensureAccount = `-- name: EnsureAccount :one
INSERT INTO accounts (id, subject, username, display_name, email, validation, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (subject) DO UPDATE SET
    username     = EXCLUDED.username,
    display_name = EXCLUDED.display_name,
    email        = EXCLUDED.email,
    validation   = EXCLUDED.validation
RETURNING id, subject, username, display_name, email, validation, created_at
`

type EnsureAccountParams struct {
	ID          string
	Subject     string
	Username    string
	DisplayName string
	Email       string
	Validation  string
	CreatedAt   time.Time
}

func (q *Queries) EnsureAccount(ctx context.Context, arg EnsureAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, ensureAccount,
		arg.ID,
		arg.Subject,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Validation,
		arg.CreatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Validation,
		&i.CreatedAt,
	)
	return i, err
}

const findStoreTokenByHash = `-- name: FindStoreTokenByHash :one
SELECT
    t.session_id, t.token_hash, t.account_id, t.description,
    t.packages, t.channels, t.permissions,
    t.valid_since, t.valid_until, t.revoked_at, t.revoked_by,
    a.id          AS acc_id,
    a.subject     AS acc_subject,
    a.username    AS acc_username,
    a.display_name AS acc_display_name,
    a.email       AS acc_email,
    a.validation  AS acc_validation,
    a.created_at  AS acc_created_at
FROM store_tokens t
JOIN accounts a ON a.id = t.account_id
WHERE t.token_hash = $1
`

type FindStoreTokenByHashRow struct {
	SessionID      string
	TokenHash      string
	AccountID      string
	Description    *string
	Packages       json.RawMessage
	Channels       json.RawMessage
	Permissions    json.RawMessage
	ValidSince     time.Time
	ValidUntil     time.Time
	RevokedAt      pgtype.Timestamptz
	RevokedBy      *string
	AccID          string
	AccSubject     string
	AccUsername    string
	AccDisplayName string
	AccEmail       string
	AccValidation  string
	AccCreatedAt   time.Time
}

func (q *Queries) FindStoreTokenByHash(ctx context.Context, tokenHash string) (FindStoreTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, findStoreTokenByHash, tokenHash)
	var i FindStoreTokenByHashRow
	err := row.Scan(
		&i.SessionID,
		&i.TokenHash,
		&i.AccountID,
		&i.Description,
		&i.Packages,
		&i.Channels,
		&i.Permissions,
		&i.ValidSince,
		&i.ValidUntil,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.AccID,
		&i.AccSubject,
		&i.AccUsername,
		&i.AccDisplayName,
		&i.AccEmail,
		&i.AccValidation,
		&i.AccCreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, subject, username, display_name, email, validation, created_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Validation,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveStoreTokens = `-- name: ListActiveStoreTokens :many
SELECT session_id, token_hash, account_id, description,
       packages, channels, permissions,
       valid_since, valid_until, revoked_at, revoked_by
FROM store_tokens
WHERE account_id = $1
  AND revoked_at IS NULL
  AND valid_until > NOW()
ORDER BY valid_since ASC
`

func (q *Queries) ListActiveStoreTokens(ctx context.Context, accountID string) ([]StoreToken, error) {
	rows, err := q.db.Query(ctx, listActiveStoreTokens, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoreToken{}
	for rows.Next() {
		var i StoreToken
		if err := rows.Scan(
			&i.SessionID,
			&i.TokenHash,
			&i.AccountID,
			&i.Description,
			&i.Packages,
			&i.Channels,
			&i.Permissions,
			&i.ValidSince,
			&i.ValidUntil,
			&i.RevokedAt,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllStoreTokens = `-- name: ListAllStoreTokens :many
SELECT session_id, token_hash, account_id, description,
       packages, channels, permissions,
       valid_since, valid_until, revoked_at, revoked_by
FROM store_tokens
WHERE account_id = $1
ORDER BY valid_since ASC
`

func (q *Queries) ListAllStoreTokens(ctx context.Context, accountID string) ([]StoreToken, error) {
	rows, err := q.db.Query(ctx, listAllStoreTokens, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoreToken{}
	for rows.Next() {
		var i StoreToken
		if err := rows.Scan(
			&i.SessionID,
			&i.TokenHash,
			&i.AccountID,
			&i.Description,
			&i.Packages,
			&i.Channels,
			&i.Permissions,
			&i.ValidSince,
			&i.ValidUntil,
			&i.RevokedAt,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeStoreToken = `-- name: RevokeStoreToken :execrows
UPDATE store_tokens
SET revoked_at = NOW(),
    revoked_by = $3
WHERE account_id = $1
  AND session_id = $2
`

type RevokeStoreTokenParams struct {
	AccountID string
	SessionID string
	RevokedBy *string
}

func (q *Queries) RevokeStoreToken(ctx context.Context, arg RevokeStoreTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeStoreToken, arg.AccountID, arg.SessionID, arg.RevokedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
