// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: charmhub_sync.sql

package repo

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCharmhubSyncRule = `-- name: CreateCharmhubSyncRule :exec
INSERT INTO charmhub_sync_rules (
    package_name, track, created_by_account_id, created_at, updated_at,
    last_sync_status, last_sync_started_at, last_sync_finished_at, last_sync_error
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateCharmhubSyncRuleParams struct {
	PackageName        string
	Track              string
	CreatedByAccountID string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	LastSyncStatus     string
	LastSyncStartedAt  pgtype.Timestamptz
	LastSyncFinishedAt pgtype.Timestamptz
	LastSyncError      *string
}

func (q *Queries) CreateCharmhubSyncRule(ctx context.Context, arg CreateCharmhubSyncRuleParams) error {
	_, err := q.db.Exec(ctx, createCharmhubSyncRule,
		arg.PackageName,
		arg.Track,
		arg.CreatedByAccountID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastSyncStatus,
		arg.LastSyncStartedAt,
		arg.LastSyncFinishedAt,
		arg.LastSyncError,
	)
	return err
}

const deleteCharmhubSyncRule = `-- name: DeleteCharmhubSyncRule :execrows
DELETE FROM charmhub_sync_rules
WHERE package_name = $1
  AND track = $2
`

type DeleteCharmhubSyncRuleParams struct {
	PackageName string
	Track       string
}

func (q *Queries) DeleteCharmhubSyncRule(ctx context.Context, arg DeleteCharmhubSyncRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCharmhubSyncRule, arg.PackageName, arg.Track)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCharmhubSyncRules = `-- name: ListCharmhubSyncRules :many
SELECT package_name, track, created_by_account_id, created_at, updated_at,
       last_sync_status, last_sync_started_at, last_sync_finished_at, last_sync_error
FROM charmhub_sync_rules
ORDER BY package_name ASC, track ASC
`

func (q *Queries) ListCharmhubSyncRules(ctx context.Context) ([]CharmhubSyncRule, error) {
	rows, err := q.db.Query(ctx, listCharmhubSyncRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharmhubSyncRule{}
	for rows.Next() {
		var i CharmhubSyncRule
		if err := rows.Scan(
			&i.PackageName,
			&i.Track,
			&i.CreatedByAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSyncStatus,
			&i.LastSyncStartedAt,
			&i.LastSyncFinishedAt,
			&i.LastSyncError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharmhubSyncRulesByPackageName = `-- name: ListCharmhubSyncRulesByPackageName :many
SELECT package_name, track, created_by_account_id, created_at, updated_at,
       last_sync_status, last_sync_started_at, last_sync_finished_at, last_sync_error
FROM charmhub_sync_rules
WHERE package_name = $1
ORDER BY track ASC
`

func (q *Queries) ListCharmhubSyncRulesByPackageName(ctx context.Context, packageName string) ([]CharmhubSyncRule, error) {
	rows, err := q.db.Query(ctx, listCharmhubSyncRulesByPackageName, packageName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharmhubSyncRule{}
	for rows.Next() {
		var i CharmhubSyncRule
		if err := rows.Scan(
			&i.PackageName,
			&i.Track,
			&i.CreatedByAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSyncStatus,
			&i.LastSyncStartedAt,
			&i.LastSyncFinishedAt,
			&i.LastSyncError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharmhubSyncRule = `-- name: UpdateCharmhubSyncRule :execrows
UPDATE charmhub_sync_rules
SET updated_at = $3,
    last_sync_status = $4,
    last_sync_started_at = $5,
    last_sync_finished_at = $6,
    last_sync_error = $7
WHERE package_name = $1
  AND track = $2
`

type UpdateCharmhubSyncRuleParams struct {
	PackageName        string
	Track              string
	UpdatedAt          time.Time
	LastSyncStatus     string
	LastSyncStartedAt  pgtype.Timestamptz
	LastSyncFinishedAt pgtype.Timestamptz
	LastSyncError      *string
}

func (q *Queries) UpdateCharmhubSyncRule(ctx context.Context, arg UpdateCharmhubSyncRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCharmhubSyncRule,
		arg.PackageName,
		arg.Track,
		arg.UpdatedAt,
		arg.LastSyncStatus,
		arg.LastSyncStartedAt,
		arg.LastSyncFinishedAt,
		arg.LastSyncError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
