// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          string
	Subject     string
	Username    string
	DisplayName string
	Email       string
	Validation  string
	IsAdmin     bool
	CreatedAt   time.Time
}

type AccountGroup struct {
	ID          string
	Slug        string
	DisplayName string
	CreatedAt   time.Time
}

type AccountGroupMember struct {
	GroupID   string
	AccountID string
}

type Package struct {
	ID                    string
	Name                  string
	Type                  string
	Private               bool
	Status                string
	OwnerAccountID        string
	HarborProject         string
	HarborPushRobotID     *int64
	HarborPushRobotName   string
	HarborPushRobotSecret string
	HarborPullRobotID     *int64
	HarborPullRobotName   string
	HarborPullRobotSecret string
	HarborSyncedAt        pgtype.Timestamptz
	Authority             *string
	Contact               *string
	DefaultTrack          *string
	Description           *string
	Summary               *string
	Title                 *string
	Website               *string
	Links                 json.RawMessage
	Media                 json.RawMessage
	TrackGuardrails       json.RawMessage
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type PackageAcl struct {
	PackageID     string
	PrincipalType string
	PrincipalID   string
	Role          string
}

type Release struct {
	ID             string
	PackageID      string
	Channel        string
	Revision       int32
	Base           json.RawMessage
	Resources      json.RawMessage
	WhenCreated    time.Time
	ExpirationDate pgtype.Timestamptz
	Progressive    *float64
}

type ResourceDefinition struct {
	ID          string
	PackageID   string
	Name        string
	Type        string
	Description string
	Filename    string
	Optional    bool
	CreatedAt   time.Time
}

type ResourceRevision struct {
	ID              string
	ResourceID      string
	Revision        int32
	PackageRevision *int32
	Name            string
	Type            string
	Description     string
	Filename        string
	CreatedAt       time.Time
	Size            int64
	Sha256          string
	Sha384          string
	Sha512          string
	Sha3384         string
	ObjectKey       string
	Bases           json.RawMessage
	Architectures   json.RawMessage
	OciImageDigest  string
	OciImageBlob    string
}

type Revision struct {
	ID           string
	PackageID    string
	Revision     int32
	Version      string
	Status       string
	CreatedAt    time.Time
	CreatedBy    string
	Size         int64
	Sha256       string
	Sha384       string
	ObjectKey    string
	MetadataYaml string
	ConfigYaml   string
	ActionsYaml  string
	BundleYaml   string
	ReadmeMd     string
	Bases        json.RawMessage
	Attributes   json.RawMessage
	Relations    json.RawMessage
	Subordinate  bool
}

type StoreToken struct {
	SessionID   string
	TokenHash   string
	AccountID   string
	Description *string
	Packages    json.RawMessage
	Channels    json.RawMessage
	Permissions json.RawMessage
	ValidSince  time.Time
	ValidUntil  time.Time
	RevokedAt   pgtype.Timestamptz
	RevokedBy   *string
}

type Track struct {
	PackageID                  string
	Name                       string
	VersionPattern             *string
	AutomaticPhasingPercentage *float64
	CreatedAt                  time.Time
}

type Upload struct {
	ID         string
	Filename   string
	ObjectKey  string
	Size       int64
	Sha256     string
	Sha384     string
	Status     string
	Kind       string
	CreatedAt  time.Time
	ApprovedAt pgtype.Timestamptz
	Revision   *int32
	Errors     json.RawMessage
}
