// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: packages.sql

package repo

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const canManagePackage = `-- name: CanManagePackage :one
SELECT EXISTS (
    SELECT 1 FROM package_acl acl
    LEFT JOIN account_group_members gm
      ON acl.principal_type = 'group' AND acl.principal_id = gm.group_id
    WHERE acl.package_id = $1
      AND acl.role = ANY($3::text[])
      AND ((acl.principal_type = 'account' AND acl.principal_id = $2)
           OR gm.account_id = $2)
) AS allowed
`

type CanManagePackageParams struct {
	PackageID   string
	PrincipalID string
	Column3     []string
}

func (q *Queries) CanManagePackage(ctx context.Context, arg CanManagePackageParams) (bool, error) {
	row := q.db.QueryRow(ctx, canManagePackage, arg.PackageID, arg.PrincipalID, arg.Column3)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const canViewPackage = `-- name: CanViewPackage :one
SELECT EXISTS (
    SELECT 1 FROM package_acl acl
    LEFT JOIN account_group_members gm
      ON acl.principal_type = 'group' AND acl.principal_id = gm.group_id
    WHERE acl.package_id = $1
      AND acl.role = ANY($3::text[])
      AND ((acl.principal_type = 'account' AND acl.principal_id = $2)
           OR gm.account_id = $2)
) AS allowed
`

type CanViewPackageParams struct {
	PackageID   string
	PrincipalID string
	Column3     []string
}

// Uses = ANY($3) so the allowed-roles list is a parameterized value, not an
// interpolated SQL fragment. This is the safe replacement for the old
// fmt.Sprintf(roleCondition) pattern.
func (q *Queries) CanViewPackage(ctx context.Context, arg CanViewPackageParams) (bool, error) {
	row := q.db.QueryRow(ctx, canViewPackage, arg.PackageID, arg.PrincipalID, arg.Column3)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const createPackage = `-- name: CreatePackage :exec
INSERT INTO packages (
    id, name, type, private, status, owner_account_id,
    harbor_project, harbor_push_robot_id, harbor_push_robot_name, harbor_push_robot_secret,
    harbor_pull_robot_id, harbor_pull_robot_name, harbor_pull_robot_secret, harbor_synced_at,
    authority, contact, default_track,
    description, summary, title, website,
    links, media, track_guardrails,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17,
    $18, $19, $20, $21,
    $22, $23, $24,
    $25, $26
)
`

type CreatePackageParams struct {
	ID                    string
	Name                  string
	Type                  string
	Private               bool
	Status                string
	OwnerAccountID        string
	HarborProject         string
	HarborPushRobotID     *int64
	HarborPushRobotName   string
	HarborPushRobotSecret string
	HarborPullRobotID     *int64
	HarborPullRobotName   string
	HarborPullRobotSecret string
	HarborSyncedAt        pgtype.Timestamptz
	Authority             *string
	Contact               *string
	DefaultTrack          *string
	Description           *string
	Summary               *string
	Title                 *string
	Website               *string
	Links                 json.RawMessage
	Media                 json.RawMessage
	TrackGuardrails       json.RawMessage
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) error {
	_, err := q.db.Exec(ctx, createPackage,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Private,
		arg.Status,
		arg.OwnerAccountID,
		arg.HarborProject,
		arg.HarborPushRobotID,
		arg.HarborPushRobotName,
		arg.HarborPushRobotSecret,
		arg.HarborPullRobotID,
		arg.HarborPullRobotName,
		arg.HarborPullRobotSecret,
		arg.HarborSyncedAt,
		arg.Authority,
		arg.Contact,
		arg.DefaultTrack,
		arg.Description,
		arg.Summary,
		arg.Title,
		arg.Website,
		arg.Links,
		arg.Media,
		arg.TrackGuardrails,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePackage = `-- name: DeletePackage :execrows
DELETE FROM packages WHERE id = $1
`

func (q *Queries) DeletePackage(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePackage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPackageByID = `-- name: GetPackageByID :one
SELECT
    p.id, p.name, p.type, p.private, p.status, p.owner_account_id,
    p.harbor_project, p.harbor_push_robot_id, p.harbor_push_robot_name, p.harbor_push_robot_secret,
    p.harbor_pull_robot_id, p.harbor_pull_robot_name, p.harbor_pull_robot_secret, p.harbor_synced_at,
    p.authority, p.contact, p.default_track, p.description, p.summary, p.title,
    p.website, p.links, p.media, p.track_guardrails, p.created_at, p.updated_at,
    a.id          AS pub_id,
    a.username    AS pub_username,
    a.display_name AS pub_display_name,
    a.email       AS pub_email,
    a.validation  AS pub_validation
FROM packages p
JOIN accounts a ON a.id = p.owner_account_id
WHERE p.id = $1
`

type GetPackageByIDRow struct {
	ID                    string
	Name                  string
	Type                  string
	Private               bool
	Status                string
	OwnerAccountID        string
	HarborProject         string
	HarborPushRobotID     *int64
	HarborPushRobotName   string
	HarborPushRobotSecret string
	HarborPullRobotID     *int64
	HarborPullRobotName   string
	HarborPullRobotSecret string
	HarborSyncedAt        pgtype.Timestamptz
	Authority             *string
	Contact               *string
	DefaultTrack          *string
	Description           *string
	Summary               *string
	Title                 *string
	Website               *string
	Links                 json.RawMessage
	Media                 json.RawMessage
	TrackGuardrails       json.RawMessage
	CreatedAt             time.Time
	UpdatedAt             time.Time
	PubID                 string
	PubUsername           string
	PubDisplayName        string
	PubEmail              string
	PubValidation         string
}

func (q *Queries) GetPackageByID(ctx context.Context, id string) (GetPackageByIDRow, error) {
	row := q.db.QueryRow(ctx, getPackageByID, id)
	var i GetPackageByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Private,
		&i.Status,
		&i.OwnerAccountID,
		&i.HarborProject,
		&i.HarborPushRobotID,
		&i.HarborPushRobotName,
		&i.HarborPushRobotSecret,
		&i.HarborPullRobotID,
		&i.HarborPullRobotName,
		&i.HarborPullRobotSecret,
		&i.HarborSyncedAt,
		&i.Authority,
		&i.Contact,
		&i.DefaultTrack,
		&i.Description,
		&i.Summary,
		&i.Title,
		&i.Website,
		&i.Links,
		&i.Media,
		&i.TrackGuardrails,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PubID,
		&i.PubUsername,
		&i.PubDisplayName,
		&i.PubEmail,
		&i.PubValidation,
	)
	return i, err
}

const getPackageByName = `-- name: GetPackageByName :one
SELECT
    p.id, p.name, p.type, p.private, p.status, p.owner_account_id,
    p.harbor_project, p.harbor_push_robot_id, p.harbor_push_robot_name, p.harbor_push_robot_secret,
    p.harbor_pull_robot_id, p.harbor_pull_robot_name, p.harbor_pull_robot_secret, p.harbor_synced_at,
    p.authority, p.contact, p.default_track, p.description, p.summary, p.title,
    p.website, p.links, p.media, p.track_guardrails, p.created_at, p.updated_at,
    a.id          AS pub_id,
    a.username    AS pub_username,
    a.display_name AS pub_display_name,
    a.email       AS pub_email,
    a.validation  AS pub_validation
FROM packages p
JOIN accounts a ON a.id = p.owner_account_id
WHERE p.name = $1
`

type GetPackageByNameRow struct {
	ID                    string
	Name                  string
	Type                  string
	Private               bool
	Status                string
	OwnerAccountID        string
	HarborProject         string
	HarborPushRobotID     *int64
	HarborPushRobotName   string
	HarborPushRobotSecret string
	HarborPullRobotID     *int64
	HarborPullRobotName   string
	HarborPullRobotSecret string
	HarborSyncedAt        pgtype.Timestamptz
	Authority             *string
	Contact               *string
	DefaultTrack          *string
	Description           *string
	Summary               *string
	Title                 *string
	Website               *string
	Links                 json.RawMessage
	Media                 json.RawMessage
	TrackGuardrails       json.RawMessage
	CreatedAt             time.Time
	UpdatedAt             time.Time
	PubID                 string
	PubUsername           string
	PubDisplayName        string
	PubEmail              string
	PubValidation         string
}

func (q *Queries) GetPackageByName(ctx context.Context, name string) (GetPackageByNameRow, error) {
	row := q.db.QueryRow(ctx, getPackageByName, name)
	var i GetPackageByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Private,
		&i.Status,
		&i.OwnerAccountID,
		&i.HarborProject,
		&i.HarborPushRobotID,
		&i.HarborPushRobotName,
		&i.HarborPushRobotSecret,
		&i.HarborPullRobotID,
		&i.HarborPullRobotName,
		&i.HarborPullRobotSecret,
		&i.HarborSyncedAt,
		&i.Authority,
		&i.Contact,
		&i.DefaultTrack,
		&i.Description,
		&i.Summary,
		&i.Title,
		&i.Website,
		&i.Links,
		&i.Media,
		&i.TrackGuardrails,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PubID,
		&i.PubUsername,
		&i.PubDisplayName,
		&i.PubEmail,
		&i.PubValidation,
	)
	return i, err
}

const getPackageOwner = `-- name: GetPackageOwner :one
SELECT private, owner_account_id FROM packages WHERE id = $1
`

type GetPackageOwnerRow struct {
	Private        bool
	OwnerAccountID string
}

func (q *Queries) GetPackageOwner(ctx context.Context, id string) (GetPackageOwnerRow, error) {
	row := q.db.QueryRow(ctx, getPackageOwner, id)
	var i GetPackageOwnerRow
	err := row.Scan(&i.Private, &i.OwnerAccountID)
	return i, err
}

const listPackagesForAccount = `-- name: ListPackagesForAccount :many
SELECT
    p.id, p.name, p.type, p.private, p.status, p.owner_account_id,
    p.harbor_project, p.harbor_push_robot_id, p.harbor_push_robot_name, p.harbor_push_robot_secret,
    p.harbor_pull_robot_id, p.harbor_pull_robot_name, p.harbor_pull_robot_secret, p.harbor_synced_at,
    p.authority, p.contact, p.default_track, p.description, p.summary, p.title,
    p.website, p.links, p.media, p.track_guardrails, p.created_at, p.updated_at,
    a.id          AS pub_id,
    a.username    AS pub_username,
    a.display_name AS pub_display_name,
    a.email       AS pub_email,
    a.validation  AS pub_validation
FROM packages p
JOIN accounts a ON a.id = p.owner_account_id
WHERE p.owner_account_id = $1
`

type ListPackagesForAccountRow struct {
	ID                    string
	Name                  string
	Type                  string
	Private               bool
	Status                string
	OwnerAccountID        string
	HarborProject         string
	HarborPushRobotID     *int64
	HarborPushRobotName   string
	HarborPushRobotSecret string
	HarborPullRobotID     *int64
	HarborPullRobotName   string
	HarborPullRobotSecret string
	HarborSyncedAt        pgtype.Timestamptz
	Authority             *string
	Contact               *string
	DefaultTrack          *string
	Description           *string
	Summary               *string
	Title                 *string
	Website               *string
	Links                 json.RawMessage
	Media                 json.RawMessage
	TrackGuardrails       json.RawMessage
	CreatedAt             time.Time
	UpdatedAt             time.Time
	PubID                 string
	PubUsername           string
	PubDisplayName        string
	PubEmail              string
	PubValidation         string
}

func (q *Queries) ListPackagesForAccount(ctx context.Context, ownerAccountID string) ([]ListPackagesForAccountRow, error) {
	rows, err := q.db.Query(ctx, listPackagesForAccount, ownerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackagesForAccountRow{}
	for rows.Next() {
		var i ListPackagesForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Private,
			&i.Status,
			&i.OwnerAccountID,
			&i.HarborProject,
			&i.HarborPushRobotID,
			&i.HarborPushRobotName,
			&i.HarborPushRobotSecret,
			&i.HarborPullRobotID,
			&i.HarborPullRobotName,
			&i.HarborPullRobotSecret,
			&i.HarborSyncedAt,
			&i.Authority,
			&i.Contact,
			&i.DefaultTrack,
			&i.Description,
			&i.Summary,
			&i.Title,
			&i.Website,
			&i.Links,
			&i.Media,
			&i.TrackGuardrails,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PubID,
			&i.PubUsername,
			&i.PubDisplayName,
			&i.PubEmail,
			&i.PubValidation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagesForAccountWithCollaborations = `-- name: ListPackagesForAccountWithCollaborations :many
SELECT
    p.id, p.name, p.type, p.private, p.status, p.owner_account_id,
    p.harbor_project, p.harbor_push_robot_id, p.harbor_push_robot_name, p.harbor_push_robot_secret,
    p.harbor_pull_robot_id, p.harbor_pull_robot_name, p.harbor_pull_robot_secret, p.harbor_synced_at,
    p.authority, p.contact, p.default_track, p.description, p.summary, p.title,
    p.website, p.links, p.media, p.track_guardrails, p.created_at, p.updated_at,
    a.id          AS pub_id,
    a.username    AS pub_username,
    a.display_name AS pub_display_name,
    a.email       AS pub_email,
    a.validation  AS pub_validation
FROM packages p
JOIN accounts a ON a.id = p.owner_account_id
WHERE p.owner_account_id = $1
   OR EXISTS (
        SELECT 1 FROM package_acl acl
        LEFT JOIN account_group_members gm
          ON acl.principal_type = 'group' AND acl.principal_id = gm.group_id
        WHERE acl.package_id = p.id
          AND ((acl.principal_type = 'account' AND acl.principal_id = $1) OR gm.account_id = $1)
   )
`

type ListPackagesForAccountWithCollaborationsRow struct {
	ID                    string
	Name                  string
	Type                  string
	Private               bool
	Status                string
	OwnerAccountID        string
	HarborProject         string
	HarborPushRobotID     *int64
	HarborPushRobotName   string
	HarborPushRobotSecret string
	HarborPullRobotID     *int64
	HarborPullRobotName   string
	HarborPullRobotSecret string
	HarborSyncedAt        pgtype.Timestamptz
	Authority             *string
	Contact               *string
	DefaultTrack          *string
	Description           *string
	Summary               *string
	Title                 *string
	Website               *string
	Links                 json.RawMessage
	Media                 json.RawMessage
	TrackGuardrails       json.RawMessage
	CreatedAt             time.Time
	UpdatedAt             time.Time
	PubID                 string
	PubUsername           string
	PubDisplayName        string
	PubEmail              string
	PubValidation         string
}

func (q *Queries) ListPackagesForAccountWithCollaborations(ctx context.Context, ownerAccountID string) ([]ListPackagesForAccountWithCollaborationsRow, error) {
	rows, err := q.db.Query(ctx, listPackagesForAccountWithCollaborations, ownerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackagesForAccountWithCollaborationsRow{}
	for rows.Next() {
		var i ListPackagesForAccountWithCollaborationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Private,
			&i.Status,
			&i.OwnerAccountID,
			&i.HarborProject,
			&i.HarborPushRobotID,
			&i.HarborPushRobotName,
			&i.HarborPushRobotSecret,
			&i.HarborPullRobotID,
			&i.HarborPullRobotName,
			&i.HarborPullRobotSecret,
			&i.HarborSyncedAt,
			&i.Authority,
			&i.Contact,
			&i.DefaultTrack,
			&i.Description,
			&i.Summary,
			&i.Title,
			&i.Website,
			&i.Links,
			&i.Media,
			&i.TrackGuardrails,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PubID,
			&i.PubUsername,
			&i.PubDisplayName,
			&i.PubEmail,
			&i.PubValidation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPackages = `-- name: SearchPackages :many
SELECT
    p.id, p.name, p.type, p.private, p.status, p.owner_account_id,
    p.harbor_project, p.harbor_push_robot_id, p.harbor_push_robot_name, p.harbor_push_robot_secret,
    p.harbor_pull_robot_id, p.harbor_pull_robot_name, p.harbor_pull_robot_secret, p.harbor_synced_at,
    p.authority, p.contact, p.default_track, p.description, p.summary, p.title,
    p.website, p.links, p.media, p.track_guardrails, p.created_at, p.updated_at,
    a.id          AS pub_id,
    a.username    AS pub_username,
    a.display_name AS pub_display_name,
    a.email       AS pub_email,
    a.validation  AS pub_validation
FROM packages p
JOIN accounts a ON a.id = p.owner_account_id
WHERE p.name ILIKE $1::text ESCAPE '\'
ORDER BY p.name ASC
`

type SearchPackagesRow struct {
	ID                    string
	Name                  string
	Type                  string
	Private               bool
	Status                string
	OwnerAccountID        string
	HarborProject         string
	HarborPushRobotID     *int64
	HarborPushRobotName   string
	HarborPushRobotSecret string
	HarborPullRobotID     *int64
	HarborPullRobotName   string
	HarborPullRobotSecret string
	HarborSyncedAt        pgtype.Timestamptz
	Authority             *string
	Contact               *string
	DefaultTrack          *string
	Description           *string
	Summary               *string
	Title                 *string
	Website               *string
	Links                 json.RawMessage
	Media                 json.RawMessage
	TrackGuardrails       json.RawMessage
	CreatedAt             time.Time
	UpdatedAt             time.Time
	PubID                 string
	PubUsername           string
	PubDisplayName        string
	PubEmail              string
	PubValidation         string
}

func (q *Queries) SearchPackages(ctx context.Context, dollar_1 string) ([]SearchPackagesRow, error) {
	rows, err := q.db.Query(ctx, searchPackages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPackagesRow{}
	for rows.Next() {
		var i SearchPackagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Private,
			&i.Status,
			&i.OwnerAccountID,
			&i.HarborProject,
			&i.HarborPushRobotID,
			&i.HarborPushRobotName,
			&i.HarborPushRobotSecret,
			&i.HarborPullRobotID,
			&i.HarborPullRobotName,
			&i.HarborPullRobotSecret,
			&i.HarborSyncedAt,
			&i.Authority,
			&i.Contact,
			&i.DefaultTrack,
			&i.Description,
			&i.Summary,
			&i.Title,
			&i.Website,
			&i.Links,
			&i.Media,
			&i.TrackGuardrails,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PubID,
			&i.PubUsername,
			&i.PubDisplayName,
			&i.PubEmail,
			&i.PubValidation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackage = `-- name: UpdatePackage :execrows
UPDATE packages SET
    private          = $2,
    status           = $3,
    harbor_project   = $4,
    harbor_push_robot_id = $5,
    harbor_push_robot_name = $6,
    harbor_push_robot_secret = $7,
    harbor_pull_robot_id = $8,
    harbor_pull_robot_name = $9,
    harbor_pull_robot_secret = $10,
    harbor_synced_at  = $11,
    authority        = $12,
    contact          = $13,
    default_track    = $14,
    description      = $15,
    summary          = $16,
    title            = $17,
    website          = $18,
    links            = $19,
    media            = $20,
    track_guardrails = $21,
    updated_at       = $22
WHERE id = $1
`

type UpdatePackageParams struct {
	ID                    string
	Private               bool
	Status                string
	HarborProject         string
	HarborPushRobotID     *int64
	HarborPushRobotName   string
	HarborPushRobotSecret string
	HarborPullRobotID     *int64
	HarborPullRobotName   string
	HarborPullRobotSecret string
	HarborSyncedAt        pgtype.Timestamptz
	Authority             *string
	Contact               *string
	DefaultTrack          *string
	Description           *string
	Summary               *string
	Title                 *string
	Website               *string
	Links                 json.RawMessage
	Media                 json.RawMessage
	TrackGuardrails       json.RawMessage
	UpdatedAt             time.Time
}

func (q *Queries) UpdatePackage(ctx context.Context, arg UpdatePackageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePackage,
		arg.ID,
		arg.Private,
		arg.Status,
		arg.HarborProject,
		arg.HarborPushRobotID,
		arg.HarborPushRobotName,
		arg.HarborPushRobotSecret,
		arg.HarborPullRobotID,
		arg.HarborPullRobotName,
		arg.HarborPullRobotSecret,
		arg.HarborSyncedAt,
		arg.Authority,
		arg.Contact,
		arg.DefaultTrack,
		arg.Description,
		arg.Summary,
		arg.Title,
		arg.Website,
		arg.Links,
		arg.Media,
		arg.TrackGuardrails,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
