// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	ApproveUpload(ctx context.Context, arg ApproveUploadParams) (int64, error)
	CanManagePackage(ctx context.Context, arg CanManagePackageParams) (bool, error)
	// Uses = ANY($3) so the allowed-roles list is a parameterized value, not an
	// interpolated SQL fragment. This is the safe replacement for the old
	// fmt.Sprintf(roleCondition) pattern.
	CanViewPackage(ctx context.Context, arg CanViewPackageParams) (bool, error)
	CreatePackage(ctx context.Context, arg CreatePackageParams) error
	CreateResourceRevision(ctx context.Context, arg CreateResourceRevisionParams) error
	CreateRevision(ctx context.Context, arg CreateRevisionParams) error
	CreateStoreToken(ctx context.Context, arg CreateStoreTokenParams) error
	CreateTrack(ctx context.Context, arg CreateTrackParams) (int64, error)
	CreateUpload(ctx context.Context, arg CreateUploadParams) error
	DeletePackage(ctx context.Context, id string) (int64, error)
	EnsureAccount(ctx context.Context, arg EnsureAccountParams) (Account, error)
	FindStoreTokenByHash(ctx context.Context, tokenHash string) (FindStoreTokenByHashRow, error)
	GetAccountByID(ctx context.Context, id string) (Account, error)
	GetPackageByID(ctx context.Context, id string) (GetPackageByIDRow, error)
	GetPackageByName(ctx context.Context, name string) (GetPackageByNameRow, error)
	GetPackageOwner(ctx context.Context, id string) (GetPackageOwnerRow, error)
	GetResourceDefinition(ctx context.Context, arg GetResourceDefinitionParams) (ResourceDefinition, error)
	GetResourceRevision(ctx context.Context, arg GetResourceRevisionParams) (ResourceRevision, error)
	GetRevisionByNumber(ctx context.Context, arg GetRevisionByNumberParams) (Revision, error)
	GetUpload(ctx context.Context, id string) (Upload, error)
	ListActiveStoreTokens(ctx context.Context, accountID string) ([]StoreToken, error)
	ListAllStoreTokens(ctx context.Context, accountID string) ([]StoreToken, error)
	ListPackagesForAccount(ctx context.Context, ownerAccountID string) ([]ListPackagesForAccountRow, error)
	ListReleases(ctx context.Context, packageID string) ([]Release, error)
	ListResourceDefinitions(ctx context.Context, packageID string) ([]ResourceDefinition, error)
	ListResourceRevisions(ctx context.Context, resourceID string) ([]ResourceRevision, error)
	ListRevisions(ctx context.Context, packageID string) ([]Revision, error)
	ListTracks(ctx context.Context, packageID string) ([]ListTracksRow, error)
	ReplaceRelease(ctx context.Context, arg ReplaceReleaseParams) error
	ResolveDefaultRelease(ctx context.Context, id string) (Release, error)
	ResolveLatestRelease(ctx context.Context, packageID string) (Release, error)
	ResolveRelease(ctx context.Context, arg ResolveReleaseParams) (Release, error)
	RevokeStoreToken(ctx context.Context, arg RevokeStoreTokenParams) (int64, error)
	SearchPackages(ctx context.Context, name string) ([]SearchPackagesRow, error)
	UpdatePackage(ctx context.Context, arg UpdatePackageParams) (int64, error)
	UpdateResourceRevision(ctx context.Context, arg UpdateResourceRevisionParams) (int64, error)
	UpsertResourceDefinition(ctx context.Context, arg UpsertResourceDefinitionParams) (ResourceDefinition, error)
}

var _ Querier = (*Queries)(nil)
