// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: releases.sql

package repo

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRelease = `-- name: DeleteRelease :execrows
DELETE FROM releases
WHERE package_id = $1
  AND channel = $2
`

type DeleteReleaseParams struct {
	PackageID string
	Channel   string
}

func (q *Queries) DeleteRelease(ctx context.Context, arg DeleteReleaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRelease, arg.PackageID, arg.Channel)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listReleases = `-- name: ListReleases :many
SELECT id, package_id, channel, revision,
       base, resources, when_created, expiration_date, progressive
FROM releases
WHERE package_id = $1
ORDER BY channel ASC
`

func (q *Queries) ListReleases(ctx context.Context, packageID string) ([]Release, error) {
	rows, err := q.db.Query(ctx, listReleases, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.Channel,
			&i.Revision,
			&i.Base,
			&i.Resources,
			&i.WhenCreated,
			&i.ExpirationDate,
			&i.Progressive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceRelease = `-- name: ReplaceRelease :exec
INSERT INTO releases (
    id, package_id, channel, revision,
    base, resources, when_created, expiration_date, progressive
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (package_id, channel) DO UPDATE SET
    revision        = EXCLUDED.revision,
    base            = EXCLUDED.base,
    resources       = EXCLUDED.resources,
    when_created    = EXCLUDED.when_created,
    expiration_date = EXCLUDED.expiration_date,
    progressive     = EXCLUDED.progressive
`

type ReplaceReleaseParams struct {
	ID             string
	PackageID      string
	Channel        string
	Revision       int32
	Base           json.RawMessage
	Resources      json.RawMessage
	WhenCreated    time.Time
	ExpirationDate pgtype.Timestamptz
	Progressive    *float64
}

func (q *Queries) ReplaceRelease(ctx context.Context, arg ReplaceReleaseParams) error {
	_, err := q.db.Exec(ctx, replaceRelease,
		arg.ID,
		arg.PackageID,
		arg.Channel,
		arg.Revision,
		arg.Base,
		arg.Resources,
		arg.WhenCreated,
		arg.ExpirationDate,
		arg.Progressive,
	)
	return err
}

const resolveDefaultRelease = `-- name: ResolveDefaultRelease :one
SELECT
    r.id, r.package_id, r.channel, r.revision,
    r.base, r.resources, r.when_created, r.expiration_date, r.progressive
FROM packages p
JOIN releases r ON r.package_id = p.id
WHERE p.id = $1
  AND (
      (p.default_track IS NOT NULL AND r.channel = p.default_track || '/stable')
   OR (p.default_track IS NULL     AND r.channel = 'latest/stable')
  )
ORDER BY r.when_created DESC
LIMIT 1
`

func (q *Queries) ResolveDefaultRelease(ctx context.Context, id string) (Release, error) {
	row := q.db.QueryRow(ctx, resolveDefaultRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Channel,
		&i.Revision,
		&i.Base,
		&i.Resources,
		&i.WhenCreated,
		&i.ExpirationDate,
		&i.Progressive,
	)
	return i, err
}

const resolveLatestRelease = `-- name: ResolveLatestRelease :one
SELECT id, package_id, channel, revision,
       base, resources, when_created, expiration_date, progressive
FROM releases
WHERE package_id = $1
ORDER BY when_created DESC
LIMIT 1
`

func (q *Queries) ResolveLatestRelease(ctx context.Context, packageID string) (Release, error) {
	row := q.db.QueryRow(ctx, resolveLatestRelease, packageID)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Channel,
		&i.Revision,
		&i.Base,
		&i.Resources,
		&i.WhenCreated,
		&i.ExpirationDate,
		&i.Progressive,
	)
	return i, err
}

const resolveRelease = `-- name: ResolveRelease :one
SELECT id, package_id, channel, revision,
       base, resources, when_created, expiration_date, progressive
FROM releases
WHERE package_id = $1
  AND channel    = $2
`

type ResolveReleaseParams struct {
	PackageID string
	Channel   string
}

func (q *Queries) ResolveRelease(ctx context.Context, arg ResolveReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, resolveRelease, arg.PackageID, arg.Channel)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Channel,
		&i.Revision,
		&i.Base,
		&i.Resources,
		&i.WhenCreated,
		&i.ExpirationDate,
		&i.Progressive,
	)
	return i, err
}
