// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package repo

import (
	"context"
	"encoding/json"
	"time"
)

const createResourceRevision = `-- name: CreateResourceRevision :exec
INSERT INTO resource_revisions (
    id, resource_id, revision, package_revision, name, type, description,
    filename, created_at, size, sha256, sha384, sha512, sha3_384,
    object_key, bases, architectures, oci_image_digest, oci_image_blob
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19
)
`

type CreateResourceRevisionParams struct {
	ID              string
	ResourceID      string
	Revision        int32
	PackageRevision *int32
	Name            string
	Type            string
	Description     string
	Filename        string
	CreatedAt       time.Time
	Size            int64
	Sha256          string
	Sha384          string
	Sha512          string
	Sha3384         string
	ObjectKey       string
	Bases           json.RawMessage
	Architectures   json.RawMessage
	OciImageDigest  string
	OciImageBlob    string
}

func (q *Queries) CreateResourceRevision(ctx context.Context, arg CreateResourceRevisionParams) error {
	_, err := q.db.Exec(ctx, createResourceRevision,
		arg.ID,
		arg.ResourceID,
		arg.Revision,
		arg.PackageRevision,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.Filename,
		arg.CreatedAt,
		arg.Size,
		arg.Sha256,
		arg.Sha384,
		arg.Sha512,
		arg.Sha3384,
		arg.ObjectKey,
		arg.Bases,
		arg.Architectures,
		arg.OciImageDigest,
		arg.OciImageBlob,
	)
	return err
}

const getResourceDefinition = `-- name: GetResourceDefinition :one
SELECT id, package_id, name, type, description, filename, optional, created_at
FROM resource_definitions
WHERE package_id = $1
  AND name       = $2
`

type GetResourceDefinitionParams struct {
	PackageID string
	Name      string
}

func (q *Queries) GetResourceDefinition(ctx context.Context, arg GetResourceDefinitionParams) (ResourceDefinition, error) {
	row := q.db.QueryRow(ctx, getResourceDefinition, arg.PackageID, arg.Name)
	var i ResourceDefinition
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Filename,
		&i.Optional,
		&i.CreatedAt,
	)
	return i, err
}

const getResourceRevision = `-- name: GetResourceRevision :one
SELECT id, resource_id, revision, package_revision, name, type, description,
       filename, created_at, size, sha256, sha384, sha512, sha3_384,
       object_key, bases, architectures, oci_image_digest, oci_image_blob
FROM resource_revisions
WHERE resource_id = $1
  AND revision    = $2
`

type GetResourceRevisionParams struct {
	ResourceID string
	Revision   int32
}

func (q *Queries) GetResourceRevision(ctx context.Context, arg GetResourceRevisionParams) (ResourceRevision, error) {
	row := q.db.QueryRow(ctx, getResourceRevision, arg.ResourceID, arg.Revision)
	var i ResourceRevision
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Revision,
		&i.PackageRevision,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Filename,
		&i.CreatedAt,
		&i.Size,
		&i.Sha256,
		&i.Sha384,
		&i.Sha512,
		&i.Sha3384,
		&i.ObjectKey,
		&i.Bases,
		&i.Architectures,
		&i.OciImageDigest,
		&i.OciImageBlob,
	)
	return i, err
}

const listResourceDefinitions = `-- name: ListResourceDefinitions :many
SELECT id, package_id, name, type, description, filename, optional, created_at
FROM resource_definitions
WHERE package_id = $1
ORDER BY name ASC
`

func (q *Queries) ListResourceDefinitions(ctx context.Context, packageID string) ([]ResourceDefinition, error) {
	rows, err := q.db.Query(ctx, listResourceDefinitions, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceDefinition{}
	for rows.Next() {
		var i ResourceDefinition
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.Filename,
			&i.Optional,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceRevisions = `-- name: ListResourceRevisions :many
SELECT id, resource_id, revision, package_revision, name, type, description,
       filename, created_at, size, sha256, sha384, sha512, sha3_384,
       object_key, bases, architectures, oci_image_digest, oci_image_blob
FROM resource_revisions
WHERE resource_id = $1
ORDER BY revision DESC
`

func (q *Queries) ListResourceRevisions(ctx context.Context, resourceID string) ([]ResourceRevision, error) {
	rows, err := q.db.Query(ctx, listResourceRevisions, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceRevision{}
	for rows.Next() {
		var i ResourceRevision
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Revision,
			&i.PackageRevision,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.Filename,
			&i.CreatedAt,
			&i.Size,
			&i.Sha256,
			&i.Sha384,
			&i.Sha512,
			&i.Sha3384,
			&i.ObjectKey,
			&i.Bases,
			&i.Architectures,
			&i.OciImageDigest,
			&i.OciImageBlob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResourceRevision = `-- name: UpdateResourceRevision :execrows
UPDATE resource_revisions
SET bases           = $4,
    architectures   = $5,
    oci_image_digest = $6,
    oci_image_blob  = $7
WHERE resource_id = $1
  AND revision    = $2
  AND id          = $3
`

type UpdateResourceRevisionParams struct {
	ResourceID     string
	Revision       int32
	ID             string
	Bases          json.RawMessage
	Architectures  json.RawMessage
	OciImageDigest string
	OciImageBlob   string
}

func (q *Queries) UpdateResourceRevision(ctx context.Context, arg UpdateResourceRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateResourceRevision,
		arg.ResourceID,
		arg.Revision,
		arg.ID,
		arg.Bases,
		arg.Architectures,
		arg.OciImageDigest,
		arg.OciImageBlob,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertResourceDefinition = `-- name: UpsertResourceDefinition :one
INSERT INTO resource_definitions (
    id, package_id, name, type, description, filename, optional, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (package_id, name) DO UPDATE SET
    type        = EXCLUDED.type,
    description = EXCLUDED.description,
    filename    = EXCLUDED.filename,
    optional    = EXCLUDED.optional
RETURNING id, package_id, name, type, description, filename, optional, created_at
`

type UpsertResourceDefinitionParams struct {
	ID          string
	PackageID   string
	Name        string
	Type        string
	Description string
	Filename    string
	Optional    bool
	CreatedAt   time.Time
}

func (q *Queries) UpsertResourceDefinition(ctx context.Context, arg UpsertResourceDefinitionParams) (ResourceDefinition, error) {
	row := q.db.QueryRow(ctx, upsertResourceDefinition,
		arg.ID,
		arg.PackageID,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.Filename,
		arg.Optional,
		arg.CreatedAt,
	)
	var i ResourceDefinition
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Filename,
		&i.Optional,
		&i.CreatedAt,
	)
	return i, err
}
