// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revisions.sql

package repo

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveUpload = `-- name: ApproveUpload :execrows
UPDATE uploads
SET approved_at = NOW(),
    revision    = $2,
    errors      = $3,
    status      = $4
WHERE id = $1
`

type ApproveUploadParams struct {
	ID       string
	Revision *int32
	Errors   json.RawMessage
	Status   string
}

func (q *Queries) ApproveUpload(ctx context.Context, arg ApproveUploadParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveUpload,
		arg.ID,
		arg.Revision,
		arg.Errors,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRevision = `-- name: CreateRevision :exec
INSERT INTO revisions (
    id, package_id, revision, version, status,
    created_at, created_by, size, sha256, sha384,
    object_key, metadata_yaml, config_yaml, actions_yaml,
    bundle_yaml, readme_md, bases, attributes, relations, subordinate
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20
)
`

type CreateRevisionParams struct {
	ID           string
	PackageID    string
	Revision     int32
	Version      string
	Status       string
	CreatedAt    time.Time
	CreatedBy    string
	Size         int64
	Sha256       string
	Sha384       string
	ObjectKey    string
	MetadataYaml string
	ConfigYaml   string
	ActionsYaml  string
	BundleYaml   string
	ReadmeMd     string
	Bases        json.RawMessage
	Attributes   json.RawMessage
	Relations    json.RawMessage
	Subordinate  bool
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) error {
	_, err := q.db.Exec(ctx, createRevision,
		arg.ID,
		arg.PackageID,
		arg.Revision,
		arg.Version,
		arg.Status,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.Size,
		arg.Sha256,
		arg.Sha384,
		arg.ObjectKey,
		arg.MetadataYaml,
		arg.ConfigYaml,
		arg.ActionsYaml,
		arg.BundleYaml,
		arg.ReadmeMd,
		arg.Bases,
		arg.Attributes,
		arg.Relations,
		arg.Subordinate,
	)
	return err
}

const createUpload = `-- name: CreateUpload :exec
INSERT INTO uploads (
    id, filename, object_key, size, sha256, sha384,
    status, kind, created_at, approved_at, revision, errors
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateUploadParams struct {
	ID         string
	Filename   string
	ObjectKey  string
	Size       int64
	Sha256     string
	Sha384     string
	Status     string
	Kind       string
	CreatedAt  time.Time
	ApprovedAt pgtype.Timestamptz
	Revision   *int32
	Errors     json.RawMessage
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) error {
	_, err := q.db.Exec(ctx, createUpload,
		arg.ID,
		arg.Filename,
		arg.ObjectKey,
		arg.Size,
		arg.Sha256,
		arg.Sha384,
		arg.Status,
		arg.Kind,
		arg.CreatedAt,
		arg.ApprovedAt,
		arg.Revision,
		arg.Errors,
	)
	return err
}

const getRevisionByNumber = `-- name: GetRevisionByNumber :one
SELECT id, package_id, revision, version, status,
       created_at, created_by, size, sha256, sha384,
       object_key, metadata_yaml, config_yaml, actions_yaml,
       bundle_yaml, readme_md, bases, attributes, relations, subordinate
FROM revisions
WHERE package_id = $1
  AND revision   = $2
`

type GetRevisionByNumberParams struct {
	PackageID string
	Revision  int32
}

func (q *Queries) GetRevisionByNumber(ctx context.Context, arg GetRevisionByNumberParams) (Revision, error) {
	row := q.db.QueryRow(ctx, getRevisionByNumber, arg.PackageID, arg.Revision)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Revision,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Size,
		&i.Sha256,
		&i.Sha384,
		&i.ObjectKey,
		&i.MetadataYaml,
		&i.ConfigYaml,
		&i.ActionsYaml,
		&i.BundleYaml,
		&i.ReadmeMd,
		&i.Bases,
		&i.Attributes,
		&i.Relations,
		&i.Subordinate,
	)
	return i, err
}

const getUpload = `-- name: GetUpload :one
SELECT id, filename, object_key, size, sha256, sha384,
       status, kind, created_at, approved_at, revision, errors
FROM uploads
WHERE id = $1
`

func (q *Queries) GetUpload(ctx context.Context, id string) (Upload, error) {
	row := q.db.QueryRow(ctx, getUpload, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ObjectKey,
		&i.Size,
		&i.Sha256,
		&i.Sha384,
		&i.Status,
		&i.Kind,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.Revision,
		&i.Errors,
	)
	return i, err
}

const listRevisions = `-- name: ListRevisions :many
SELECT id, package_id, revision, version, status,
       created_at, created_by, size, sha256, sha384,
       object_key, metadata_yaml, config_yaml, actions_yaml,
       bundle_yaml, readme_md, bases, attributes, relations, subordinate
FROM revisions
WHERE package_id = $1
ORDER BY revision DESC
`

func (q *Queries) ListRevisions(ctx context.Context, packageID string) ([]Revision, error) {
	rows, err := q.db.Query(ctx, listRevisions, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Revision{}
	for rows.Next() {
		var i Revision
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.Revision,
			&i.Version,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Size,
			&i.Sha256,
			&i.Sha384,
			&i.ObjectKey,
			&i.MetadataYaml,
			&i.ConfigYaml,
			&i.ActionsYaml,
			&i.BundleYaml,
			&i.ReadmeMd,
			&i.Bases,
			&i.Attributes,
			&i.Relations,
			&i.Subordinate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
