// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracks.sql

package repo

import (
	"context"
	"time"
)

const createTrack = `-- name: CreateTrack :execrows
INSERT INTO tracks (package_id, name, version_pattern, automatic_phasing_percentage, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type CreateTrackParams struct {
	PackageID                  string
	Name                       string
	VersionPattern             *string
	AutomaticPhasingPercentage *float64
	CreatedAt                  time.Time
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (int64, error) {
	result, err := q.db.Exec(ctx, createTrack,
		arg.PackageID,
		arg.Name,
		arg.VersionPattern,
		arg.AutomaticPhasingPercentage,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTracks = `-- name: ListTracks :many
SELECT name, version_pattern, automatic_phasing_percentage, created_at
FROM tracks
WHERE package_id = $1
ORDER BY created_at ASC
`

type ListTracksRow struct {
	Name                       string
	VersionPattern             *string
	AutomaticPhasingPercentage *float64
	CreatedAt                  time.Time
}

func (q *Queries) ListTracks(ctx context.Context, packageID string) ([]ListTracksRow, error) {
	rows, err := q.db.Query(ctx, listTracks, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTracksRow{}
	for rows.Next() {
		var i ListTracksRow
		if err := rows.Scan(
			&i.Name,
			&i.VersionPattern,
			&i.AutomaticPhasingPercentage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
