// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_gc.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStaleUploads = `-- name: DeleteStaleUploads :execrows
DELETE FROM uploads
WHERE status != 'approved'
  AND created_at < NOW() - $1::interval
`

func (q *Queries) DeleteStaleUploads(ctx context.Context, dollar_1 pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleUploads, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
