GO      ?= go
BIN_DIR ?= $(CURDIR)/.bin
SHARED_DOCKER_NETWORK ?= charm-registry-shared
HARBOR_COMPOSE := $(CURDIR)/deploy/harbor/vendor/harbor/docker-compose.yml

.PHONY: help fmt tidy tidy-check test test-race coverage vet build run lint vuln gosec sqlc-diff audit check up down install-cert harbor-prepare harbor-up harbor-down

help:
	@printf "%s\n" \
		"make fmt          - format Go code" \
		"make tidy         - tidy and verify Go modules" \
		"make tidy-check   - tidy, verify, and assert go.mod/go.sum are unchanged (CI)" \
		"make test         - run unit tests" \
		"make test-race    - run tests with the race detector" \
		"make coverage     - run tests with coverage and print report" \
		"make vet          - run go vet" \
		"make lint         - run golangci-lint" \
		"make vuln         - run govulncheck" \
		"make gosec        - run gosec static analysis" \
		"make sqlc-diff    - verify sqlc-generated code is up to date" \
		"make audit        - run lint, tests, and security checks" \
		"make build        - build the registry binary" \
		"make run          - run the registry locally" \
		"make harbor-prepare - download and render the vendored Harbor deployment" \
		"make harbor-up    - start the Harbor OCI stack" \
		"make up           - start the local compose stack with Harbor" \
		"make install-cert - install the local registry CA into the system trust store (run once after first 'make up', requires sudo)" \
		"make harbor-down  - stop the Harbor OCI stack" \
		"make down         - stop the local compose stack"

fmt:
	$(GO) fmt ./...

tidy:
	$(GO) mod tidy
	$(GO) mod verify

# Ensures go.mod/go.sum are already tidy from the current worktree state.
# This stays useful both in CI and on feature branches with unrelated changes.
tidy-check:
	@before_mod=$$(cat go.mod); \
	before_sum=$$(cat go.sum); \
	$(GO) mod verify; \
	$(GO) mod tidy; \
	test "$$before_mod" = "$$(cat go.mod)"; \
	test "$$before_sum" = "$$(cat go.sum)"

# Packages to unit-test: exclude infrastructure wiring (internal/app) that
# requires live external services, and sqlc-generated code (internal/repo/db).
_UNIT_PKGS = $(shell $(GO) list ./internal/... | grep -Ev '/(app|repo/db)$$')

test:
	$(GO) list ./internal/... | grep -Ev '/(app|repo/db)$$' | xargs $(GO) test

test-race:
	$(GO) list ./internal/... | grep -Ev '/(app|repo/db)$$' | xargs $(GO) test -race

coverage:
	$(GO) list ./internal/... | grep -Ev '/(app|repo/db)$$' | \
		xargs $(GO) test -race -coverprofile=coverage.out -covermode=atomic
	grep -v 'internal/repo/postgres' coverage.out > coverage_unit.out
	$(GO) tool cover -func=coverage_unit.out

vet:
	$(GO) vet ./...

build:
	mkdir -p $(BIN_DIR)
	CGO_ENABLED=0 $(GO) build -trimpath -buildvcs=true -o $(BIN_DIR)/charm-registry ./cmd/charm-registry

run:
	$(GO) run ./cmd/charm-registry

lint:
	$(GO) tool golangci-lint run

vuln:
	$(GO) tool govulncheck ./...

# internal/repo/db is sqlc-generated; G101 false-positives on SQL string
# constants are suppressed by excluding the directory from the scan.
gosec:
	$(GO) tool gosec -exclude-dir=internal/repo/db ./...

sqlc-diff:
	$(GO) tool sqlc diff

audit: tidy vet lint test vuln gosec

check: fmt audit

harbor-prepare:
	docker network inspect $(SHARED_DOCKER_NETWORK) >/dev/null 2>&1 || docker network create $(SHARED_DOCKER_NETWORK)
	./deploy/harbor/generate-certs.sh
	./deploy/harbor/prepare.sh

harbor-up: harbor-prepare
	- docker compose down --remove-orphans >/dev/null 2>&1
	docker compose up -d minio create-buckets
	docker compose -f $(HARBOR_COMPOSE) up -d

up: harbor-up
	docker compose up --build -d postgres charm-registry

harbor-down:
	- docker compose -f $(HARBOR_COMPOSE) down -v

# Install the self-signed CA generated by `make up` into the system trust
# store so that skopeo (used by charmcraft) trusts the local OCI registry.
# Run once after the first `make up`; safe to re-run.
# Supports Ubuntu/Debian (update-ca-certificates) and Fedora/RHEL (update-ca-trust).
install-cert:
	@test -f certs/ca.crt || (echo "ERROR: certs/ca.crt not found — run 'make up' first." && exit 1)
	@if command -v update-ca-certificates >/dev/null 2>&1; then \
		sudo cp certs/ca.crt /usr/local/share/ca-certificates/charm-registry-ca.crt && \
		sudo update-ca-certificates && \
		echo "CA installed (Debian/Ubuntu)."; \
	elif command -v update-ca-trust >/dev/null 2>&1; then \
		sudo cp certs/ca.crt /etc/pki/ca-trust/source/anchors/charm-registry-ca.crt && \
		sudo update-ca-trust extract && \
		echo "CA installed (Fedora/RHEL)."; \
	else \
		echo "Unsupported distro — copy certs/ca.crt into your system CA bundle manually." && exit 1; \
	fi

down:
	- docker compose down -v
	- docker compose -f $(HARBOR_COMPOSE) down -v
